apiVersion: v1
kind: Service
metadata:
  labels:
    app: nifi
  name: nifi
  namespace: nifi
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: nifi
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nifi
  namespace: nifi
  labels:
    app: nifi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nifi
    spec:
      containers:
      - name: nifi
        command: ["/opt/nifi/scripts/start.sh"]
        image: apache/nifi
        ports:
          - containerPort: 8080
            name: nifi